# Generated by Django 5.0.4 on 2024-04-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_userevent_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='registration_date',
        ),
        migrations.AddField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
