# Generated by Django 5.0.4 on 2024-04-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_userevent_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
    ]
