# Generated by Django 5.0.4 on 2024-04-25 04:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_capacity_event_occupancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://via.placeholder.com/300', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
